tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/core"

cask "dropbox"
cask "iterm2"
cask "spotify"
cask "superduper"

brew "mas"
brew "fzf"
brew "git"
brew "imagemagick"
brew "mmv"
brew "ruby-build"
brew "rbenv"
brew "rbenv-aliases"
brew "the_silver_searcher"
brew "tmux"
brew "vim"

mas "1Blocker", id: 1107421413
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
