require "socket"

tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/core"

cask "arq"
cask "appzapper"
cask "dropbox"
cask "spotify"
cask "superduper"

# 1Password 6.app
# Audacity
# Billings.app
# MoneyWell.app
# MoneyWorks Express.app
# SketchUp 2017

brew "coreutils"
brew "fzf"
brew "git"
brew "htop"
brew "imagemagick"
brew "jq"
brew "jsonpp"
brew "mas"
brew "mmv"
brew "rbenv"
brew "rbenv-aliases"
brew "ruby-build"
brew "the_silver_searcher"
brew "tmux"
brew "vim", args: ["without-python"]

mas "1Blocker", id: 1107421413
mas "Caffeine", id: 411246225
mas "Cascadea", id: 1432182561
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Slack", id: 803453959
mas "Xcode", id: 497799835

if ["Philips-MBP"].include?(Socket.gethostname)
  brew "leiningen"
  brew "redis", restart_service: true
  brew "roundup"
  cask "flux"
  cask "alfred"
  cask "dash"
  cask "docker"
  cask "iterm2-beta"
  cask "macdown"
  cask "max"
  cask "piezo"
  cask "postgres"
  cask "powerphotos"
  cask "qlcolorcode"
  cask "qlmarkdown"
  cask "qlstephen"
  cask "quicklook-json"
  cask "virtualbox"
else
  cask "iterm2"
  mas "GarageBand", id: 682658836
end

