[[ -s "$HOME/.bash_profile_local" ]] && source "$HOME/.bash_profile_local"

[ -r ~/.bashrc ] && source "$HOME/.bashrc"

[[ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ]] && . "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"
